[package]
name = "mtty-lsp"
description = "Language Server Protocol client for mtty's editor pane"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
mtty-platform = { path = "../term-platform" }
mtty-editor = { path = "../term-editor" }
serde_json = "1.0"
