[package]
name = "miao-term-render"
description = "wgpu-based glyph-grid renderer for miao-term"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
glyphon = "0.7"
miao-term-core = { path = "../term-core" }
wgpu = "23"
