[package]
name = "mtty-render"
description = "wgpu-based glyph-grid renderer for mtty"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
glyphon = "0.7"
mtty-core = { path = "../mtty-core" }
wgpu = "23"

[dev-dependencies]
pollster = "0.4"
